# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.2"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
nvim-cmp = "scm"
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
"bufferline.nvim" = "4.9.0"
"lualine.nvim" = "scm"
nvim-web-devicons = "0.100"
"gitsigns.nvim" = "0.9.0"
tree-sitter-markdown = "0.0.37"
tree-sitter-rust = "0.0.37"
tree-sitter-toml = "0.0.31"
"tokyonight.nvim" = "4.11.0"
"which-key.nvim" = "3.14.1"
"mini.icons" = "0.14.0"
"dropbar.nvim" = "9.0.2"
"rocks-git.nvim" = "2.5.2"

[plugins.vim-suda]
git = "lambdalisue/vim-suda"
rev = "v1.2.4"
